gen:
  api_key: vPDgaw8Pr6HpmEuS25ahRAhHJZgBcWWNGrWuy9GK
  # prompt needs to be in double quotes to render correctly
  prompt: "table_10083598_1 <c> No <t> real <c> Date <t> text <c> Round <t> text <c> Circuit <t> text <c> Pole-Position <t> text <c> Fastest-Lap <t> text <c> Race-winner <t> text <c> Report <t> text <i>"
  model_id: 48a1df35-70c4-480c-ab39-fe075b0f843c-ft
  max_tokens: 50
  temperature: 0.2
  k: 0
  p: 0.75
  frequency_penalty: 0
  presence_penalty: 0
  stop_sequences: [</s>]
  return_likelihoods: NONE
  separator: --SEPARATOR--
bq:
  credentials: place_holder
  test_sql: 'SELECT body FROM `valued-sight-253418.data.reddit` WHERE subreddit = "worldnews" and ups > 300 LIMIT 5'
stream:
  default_input: What was the date of the race in Misano?